"""Unit tests for the swappable LLM provider abstraction (Ollama vs Gemini google-genai SDK)."""
from unittest.mock import MagicMock

import pytest
from app.core.config import settings
from app.services.llm_service import LLMServiceError, generate_completion, generate_tool_response


@pytest.mark.asyncio
async def test_generate_completion_ollama_path(monkeypatch):
    """When LLM_PROVIDER='ollama', generate_completion routes to Ollama API."""
    monkeypatch.setattr(settings, "LLM_PROVIDER", "ollama")

    class MockResponse:
        def raise_for_status(self):
            pass

        def json(self):
            return {"response": "Answer from Ollama local model."}

    async def mock_post(self, url, *args, **kwargs):
        return MockResponse()

    monkeypatch.setattr("httpx.AsyncClient.post", mock_post)

    res = await generate_completion("What is our leave policy?")
    assert res == "Answer from Ollama local model."


@pytest.mark.asyncio
async def test_generate_completion_gemini_path(monkeypatch):
    """When LLM_PROVIDER='gemini', generate_completion routes to Google Gemini API (google-genai)."""
    monkeypatch.setattr(settings, "LLM_PROVIDER", "gemini")
    monkeypatch.setattr(settings, "GEMINI_API_KEY", "test-gemini-key")
    monkeypatch.setattr(settings, "GEMINI_MODEL", "gemini-2.0-flash")

    mock_client = MagicMock()
    mock_response = MagicMock()
    mock_response.text = "Answer generated by Gemini 2.0 Flash API."
    mock_client.models.generate_content.return_value = mock_response

    mock_genai_module = MagicMock()
    mock_genai_module.Client.return_value = mock_client

    monkeypatch.setattr("google.genai.Client", mock_genai_module.Client)

    res = await generate_completion("What is our leave policy?")
    assert res == "Answer generated by Gemini 2.0 Flash API."

    # Verify Gemini Client initialization and generate_content call
    mock_genai_module.Client.assert_called_once_with(api_key="test-gemini-key")
    mock_client.models.generate_content.assert_called_once_with(
        model="gemini-2.0-flash",
        contents="What is our leave policy?",
    )


@pytest.mark.asyncio
async def test_generate_completion_gemini_missing_key_raises_error(monkeypatch):
    """When LLM_PROVIDER='gemini' but GEMINI_API_KEY is empty, a clean LLMServiceError is raised."""
    monkeypatch.setattr(settings, "LLM_PROVIDER", "gemini")
    monkeypatch.setattr(settings, "GEMINI_API_KEY", "")

    with pytest.raises(LLMServiceError) as exc_info:
        await generate_completion("Test prompt")

    assert "GEMINI_API_KEY is not configured" in str(exc_info.value)


@pytest.mark.asyncio
async def test_generate_completion_invalid_provider_raises_error(monkeypatch):
    """When LLM_PROVIDER is invalid, LLMServiceError is raised."""
    monkeypatch.setattr(settings, "LLM_PROVIDER", "invalid_provider")

    with pytest.raises(LLMServiceError) as exc_info:
        await generate_completion("Test prompt")

    assert "Unsupported LLM_PROVIDER" in str(exc_info.value)


# ── generate_tool_response() retry behavior ──────────────────────────


@pytest.mark.asyncio
async def test_generate_tool_response_retries_once_then_succeeds(monkeypatch):
    """A transient failure on the first attempt shouldn't surface at all if
    the retry succeeds — the caller should just get the real answer."""
    calls = {"count": 0}

    async def flaky_completion(prompt: str) -> str:
        calls["count"] += 1
        if calls["count"] == 1:
            raise RuntimeError("simulated transient failure")
        return "Here is your synthesized answer."

    monkeypatch.setattr("app.services.llm_service.generate_completion", flaky_completion)

    result = await generate_tool_response("What's my latest email?", "[GMAIL DATA] ...")
    assert result == "Here is your synthesized answer."
    assert calls["count"] == 2


@pytest.mark.asyncio
async def test_generate_tool_response_raises_after_exhausting_retries(monkeypatch):
    """If every attempt fails, generate_tool_response raises (rather than
    silently returning something) so the caller (chat.py) knows to fall
    back to something safe instead of assuming success."""
    calls = {"count": 0}

    async def always_fails(prompt: str) -> str:
        calls["count"] += 1
        raise RuntimeError("simulated persistent failure")

    monkeypatch.setattr("app.services.llm_service.generate_completion", always_fails)

    with pytest.raises(RuntimeError, match="simulated persistent failure"):
        await generate_tool_response("What's my latest email?", "[GMAIL DATA] ...")
    # default retries=1 means exactly 2 attempts total (1 retry), not more
    assert calls["count"] == 2
