"""Unit tests for the swappable LLM provider abstraction (Ollama vs Gemini google-genai SDK)."""
from unittest.mock import MagicMock

import pytest

from app.core.config import settings
from app.services.llm_service import LLMServiceError, generate_completion


@pytest.mark.asyncio
async def test_generate_completion_ollama_path(monkeypatch):
    """When LLM_PROVIDER='ollama', generate_completion routes to Ollama API."""
    monkeypatch.setattr(settings, "LLM_PROVIDER", "ollama")

    class MockResponse:
        def raise_for_status(self):
            pass

        def json(self):
            return {"response": "Answer from Ollama local model."}

    async def mock_post(self, url, *args, **kwargs):
        return MockResponse()

    monkeypatch.setattr("httpx.AsyncClient.post", mock_post)

    res = await generate_completion("What is our leave policy?")
    assert res == "Answer from Ollama local model."


@pytest.mark.asyncio
async def test_generate_completion_gemini_path(monkeypatch):
    """When LLM_PROVIDER='gemini', generate_completion routes to Google Gemini API (google-genai)."""
    monkeypatch.setattr(settings, "LLM_PROVIDER", "gemini")
    monkeypatch.setattr(settings, "GEMINI_API_KEY", "test-gemini-key")
    monkeypatch.setattr(settings, "GEMINI_MODEL", "gemini-2.0-flash")

    mock_client = MagicMock()
    mock_response = MagicMock()
    mock_response.text = "Answer generated by Gemini 2.0 Flash API."
    mock_client.models.generate_content.return_value = mock_response

    mock_genai_module = MagicMock()
    mock_genai_module.Client.return_value = mock_client

    monkeypatch.setattr("google.genai.Client", mock_genai_module.Client)

    res = await generate_completion("What is our leave policy?")
    assert res == "Answer generated by Gemini 2.0 Flash API."

    # Verify Gemini Client initialization and generate_content call
    mock_genai_module.Client.assert_called_once_with(api_key="test-gemini-key")
    mock_client.models.generate_content.assert_called_once_with(
        model="gemini-2.0-flash",
        contents="What is our leave policy?",
    )


@pytest.mark.asyncio
async def test_generate_completion_gemini_missing_key_raises_error(monkeypatch):
    """When LLM_PROVIDER='gemini' but GEMINI_API_KEY is empty, a clean LLMServiceError is raised."""
    monkeypatch.setattr(settings, "LLM_PROVIDER", "gemini")
    monkeypatch.setattr(settings, "GEMINI_API_KEY", "")

    with pytest.raises(LLMServiceError) as exc_info:
        await generate_completion("Test prompt")

    assert "GEMINI_API_KEY is not configured" in str(exc_info.value)


@pytest.mark.asyncio
async def test_generate_completion_invalid_provider_raises_error(monkeypatch):
    """When LLM_PROVIDER is invalid, LLMServiceError is raised."""
    monkeypatch.setattr(settings, "LLM_PROVIDER", "invalid_provider")

    with pytest.raises(LLMServiceError) as exc_info:
        await generate_completion("Test prompt")

    assert "Unsupported LLM_PROVIDER" in str(exc_info.value)
