"""Unit tests for the swappable LLM provider abstraction (Ollama vs Gemini google-genai SDK)."""
from unittest.mock import MagicMock

import pytest
from app.core.config import settings
from app.services.llm_service import LLMServiceError, generate_completion, generate_tool_response


@pytest.mark.asyncio
async def test_generate_completion_ollama_path(monkeypatch):
    """When LLM_PROVIDER='ollama', generate_completion routes to Ollama API."""
    monkeypatch.setattr(settings, "LLM_PROVIDER", "ollama")

    class MockResponse:
        def raise_for_status(self):
            pass

        def json(self):
            return {"response": "Answer from Ollama local model."}

    async def mock_post(self, url, *args, **kwargs):
        return MockResponse()

    monkeypatch.setattr("httpx.AsyncClient.post", mock_post)

    res = await generate_completion("What is our leave policy?")
    assert res == "Answer from Ollama local model."


@pytest.mark.asyncio
async def test_generate_completion_gemini_path(monkeypatch):
    """When LLM_PROVIDER='gemini', generate_completion routes to Google Gemini API (google-genai).

    Uses "gemini-flash-latest" rather than "gemini-2.0-flash" deliberately —
    the latter is one of the two retired model names _generate_gemini_completion
    silently substitutes for "gemini-3.6-flash" (see the dedicated
    auto-upgrade test below), which would make this test about that
    substitution instead of the basic routing plumbing it's meant to cover.
    """
    monkeypatch.setattr(settings, "LLM_PROVIDER", "gemini")
    monkeypatch.setattr(settings, "GEMINI_API_KEY", "test-gemini-key")
    monkeypatch.setattr(settings, "GEMINI_MODEL", "gemini-flash-latest")

    mock_client = MagicMock()
    mock_response = MagicMock()
    mock_response.text = "Answer generated by Gemini Flash API."
    mock_client.models.generate_content.return_value = mock_response

    mock_genai_module = MagicMock()
    mock_genai_module.Client.return_value = mock_client

    monkeypatch.setattr("google.genai.Client", mock_genai_module.Client)

    res = await generate_completion("What is our leave policy?")
    assert res == "Answer generated by Gemini Flash API."

    # Verify Gemini Client initialization and generate_content call
    mock_genai_module.Client.assert_called_once_with(api_key="test-gemini-key")
    mock_client.models.generate_content.assert_called_once_with(
        model="gemini-flash-latest",
        contents="What is our leave policy?",
    )


@pytest.mark.asyncio
async def test_generate_completion_gemini_auto_upgrades_retired_model_names(monkeypatch):
    """A configured GEMINI_MODEL of "gemini-2.0-flash" or "gemini-2.5-flash"
    (both retired by Google) is silently substituted with "gemini-3.6-flash"
    BEFORE the call is even attempted — not just as a failure fallback."""
    monkeypatch.setattr(settings, "LLM_PROVIDER", "gemini")
    monkeypatch.setattr(settings, "GEMINI_API_KEY", "test-gemini-key")
    monkeypatch.setattr(settings, "GEMINI_MODEL", "gemini-2.0-flash")

    mock_client = MagicMock()
    mock_response = MagicMock()
    mock_response.text = "Answer from the upgraded model."
    mock_client.models.generate_content.return_value = mock_response

    mock_genai_module = MagicMock()
    mock_genai_module.Client.return_value = mock_client
    monkeypatch.setattr("google.genai.Client", mock_genai_module.Client)

    res = await generate_completion("What is our leave policy?")
    assert res == "Answer from the upgraded model."
    mock_client.models.generate_content.assert_called_once_with(
        model="gemini-3.6-flash",
        contents="What is our leave policy?",
    )


@pytest.mark.asyncio
async def test_generate_completion_gemini_falls_back_on_any_failure(monkeypatch):
    """Resilience lives in exactly one place: if the configured model's call
    fails for ANY reason (not just the two retired names above), one more
    attempt is made with the fallback model before giving up. This is the
    single mechanism generate_tool_response() now relies on instead of
    retrying at its own level too."""
    monkeypatch.setattr(settings, "LLM_PROVIDER", "gemini")
    monkeypatch.setattr(settings, "GEMINI_API_KEY", "test-gemini-key")
    monkeypatch.setattr(settings, "GEMINI_MODEL", "gemini-flash-latest")

    mock_client = MagicMock()
    mock_response = MagicMock()
    mock_response.text = "Answer from the fallback model."
    # first call (the configured model) raises, second call (the fallback
    # model) succeeds
    mock_client.models.generate_content.side_effect = [
        RuntimeError("simulated transient failure"),
        mock_response,
    ]

    mock_genai_module = MagicMock()
    mock_genai_module.Client.return_value = mock_client
    monkeypatch.setattr("google.genai.Client", mock_genai_module.Client)

    res = await generate_completion("What is our leave policy?")
    assert res == "Answer from the fallback model."
    assert mock_client.models.generate_content.call_count == 2
    first_call, second_call = mock_client.models.generate_content.call_args_list
    assert first_call.kwargs["model"] == "gemini-flash-latest"
    assert second_call.kwargs["model"] == "gemini-3.6-flash"


@pytest.mark.asyncio
async def test_generate_completion_gemini_raises_if_fallback_also_fails(monkeypatch):
    """If both the configured model AND the fallback model fail, the error
    surfaces — there's no third attempt. Exactly 2 real API calls total,
    not more, for one logical completion request."""
    monkeypatch.setattr(settings, "LLM_PROVIDER", "gemini")
    monkeypatch.setattr(settings, "GEMINI_API_KEY", "test-gemini-key")
    monkeypatch.setattr(settings, "GEMINI_MODEL", "gemini-flash-latest")

    mock_client = MagicMock()
    mock_client.models.generate_content.side_effect = RuntimeError("simulated persistent failure")

    mock_genai_module = MagicMock()
    mock_genai_module.Client.return_value = mock_client
    monkeypatch.setattr("google.genai.Client", mock_genai_module.Client)

    with pytest.raises(LLMServiceError):
        await generate_completion("What is our leave policy?")
    assert mock_client.models.generate_content.call_count == 2


@pytest.mark.asyncio
async def test_generate_completion_gemini_missing_key_raises_error(monkeypatch):
    """When LLM_PROVIDER='gemini' but GEMINI_API_KEY is empty, a clean LLMServiceError is raised."""
    monkeypatch.setattr(settings, "LLM_PROVIDER", "gemini")
    monkeypatch.setattr(settings, "GEMINI_API_KEY", "")

    with pytest.raises(LLMServiceError) as exc_info:
        await generate_completion("Test prompt")

    assert "GEMINI_API_KEY is not configured" in str(exc_info.value)


@pytest.mark.asyncio
async def test_generate_completion_invalid_provider_raises_error(monkeypatch):
    """When LLM_PROVIDER is invalid, LLMServiceError is raised."""
    monkeypatch.setattr(settings, "LLM_PROVIDER", "invalid_provider")

    with pytest.raises(LLMServiceError) as exc_info:
        await generate_completion("Test prompt")

    assert "Unsupported LLM_PROVIDER" in str(exc_info.value)


# ── generate_tool_response() ─────────────────────────────────────────
#
# No retry loop lives here anymore — it used to, but that stacked on top of
# _generate_gemini_completion()'s own retry-with-a-fallback-model behavior
# (tested above), multiplying a single failure into up to 4 real API calls
# instead of 2. Resilience now lives in exactly one place; these tests just
# confirm this function is a plain, honest pass-through to it.


@pytest.mark.asyncio
async def test_generate_tool_response_returns_completion_result(monkeypatch):
    """Plain pass-through: whatever generate_completion() returns is what
    the caller gets, with no extra attempts at this level."""
    calls = {"count": 0}

    async def mock_completion(prompt: str) -> str:
        calls["count"] += 1
        return "Here is your synthesized answer."

    monkeypatch.setattr("app.services.llm_service.generate_completion", mock_completion)

    result = await generate_tool_response("What's my latest email?", "[GMAIL DATA] ...")
    assert result == "Here is your synthesized answer."
    assert calls["count"] == 1


@pytest.mark.asyncio
async def test_generate_tool_response_propagates_failure_without_retrying(monkeypatch):
    """If generate_completion() fails, generate_tool_response() raises
    immediately — it must NOT retry at this level too, since
    _generate_gemini_completion() one level down already tried a fallback
    model before this exception ever surfaced. The caller (chat.py) is
    responsible for falling back to something safe from here."""
    calls = {"count": 0}

    async def always_fails(prompt: str) -> str:
        calls["count"] += 1
        raise RuntimeError("simulated failure, already retried one level down")

    monkeypatch.setattr("app.services.llm_service.generate_completion", always_fails)

    with pytest.raises(RuntimeError, match="simulated failure"):
        await generate_tool_response("What's my latest email?", "[GMAIL DATA] ...")
    assert calls["count"] == 1
