"""create_phase_1_workflow_tables

Revision ID: 9dbab067b54e
Revises: 'e34f5a6b7c8d'
Create Date: 2026-08-05 15:25:21.035267

"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '9dbab067b54e'
down_revision: Union[str, None] = 'e34f5a6b7c8d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('workflows',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('trigger_type', sa.Enum('MANUAL', 'SCHEDULED', 'EVENT', 'WEBHOOK', name='workflowtriggertype'), server_default='MANUAL', nullable=False),
    sa.Column('status', sa.Enum('DRAFT', 'ACTIVE', 'INACTIVE', 'ARCHIVED', name='workflowstatus'), server_default='ACTIVE', nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('config', sa.JSON(), nullable=True),
    sa.Column('created_by_id', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_workflows_id'), 'workflows', ['id'], unique=False)
    op.create_index(op.f('ix_workflows_title'), 'workflows', ['title'], unique=False)
    op.create_table('workflow_runs_v2',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('workflow_id', sa.String(), nullable=False),
    sa.Column('triggered_by_id', sa.String(), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'AWAITING_APPROVAL', 'RUNNING', 'COMPLETED', 'FAILED', 'CANCELLED', name='workflowrunstatus'), server_default='PENDING', nullable=False),
    sa.Column('inputs', sa.JSON(), nullable=True),
    sa.Column('outputs', sa.JSON(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['triggered_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['workflow_id'], ['workflows.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_workflow_runs_v2_id'), 'workflow_runs_v2', ['id'], unique=False)
    op.create_index(op.f('ix_workflow_runs_v2_status'), 'workflow_runs_v2', ['status'], unique=False)
    op.create_index(op.f('ix_workflow_runs_v2_workflow_id'), 'workflow_runs_v2', ['workflow_id'], unique=False)
    op.create_table('workflow_approvals',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('workflow_run_id', sa.String(), nullable=False),
    sa.Column('step_key', sa.String(length=100), nullable=False),
    sa.Column('approver_id', sa.String(), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'APPROVED', 'REJECTED', name='workflowapprovalstatus'), server_default='PENDING', nullable=False),
    sa.Column('prompt', sa.Text(), nullable=False),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('decided_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['approver_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['workflow_run_id'], ['workflow_runs_v2.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_workflow_approvals_id'), 'workflow_approvals', ['id'], unique=False)
    op.create_index(op.f('ix_workflow_approvals_status'), 'workflow_approvals', ['status'], unique=False)
    op.create_index(op.f('ix_workflow_approvals_workflow_run_id'), 'workflow_approvals', ['workflow_run_id'], unique=False)
    op.create_table('workflow_step_runs',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('workflow_run_id', sa.String(), nullable=False),
    sa.Column('step_key', sa.String(length=100), nullable=False),
    sa.Column('step_type', sa.String(length=100), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'AWAITING_APPROVAL', 'RUNNING', 'COMPLETED', 'FAILED', 'CANCELLED', name='workflowrunstatus'), server_default='PENDING', nullable=False),
    sa.Column('input_data', sa.JSON(), nullable=True),
    sa.Column('output_data', sa.JSON(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['workflow_run_id'], ['workflow_runs_v2.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_workflow_step_runs_id'), 'workflow_step_runs', ['id'], unique=False)
    op.create_index(op.f('ix_workflow_step_runs_workflow_run_id'), 'workflow_step_runs', ['workflow_run_id'], unique=False)
    op.drop_index(op.f('ix_chunks_embedding_hnsw'), table_name='chunks', postgresql_ops={'embedding': 'vector_cosine_ops'}, postgresql_using='hnsw')
    op.alter_column('integrations', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_index(op.f('ix_meeting_summaries_embedding_hnsw'), table_name='meeting_summaries', postgresql_ops={'embedding': 'vector_cosine_ops'}, postgresql_using='hnsw')
    op.drop_index(op.f('ix_meetings_organizer_user_id'), table_name='meetings')
    op.alter_column('oauth_tokens', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('users', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('true'))
    op.alter_column('users', 'is_superuser',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    op.alter_column('users', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_column('users', 'avatar_base64')
    op.alter_column('workflow_runs', 'started_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('workflow_runs', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('workflow_runs', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('workflow_runs', 'started_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.add_column('users', sa.Column('avatar_base64', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.alter_column('users', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('users', 'is_superuser',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    op.alter_column('users', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('true'))
    op.alter_column('oauth_tokens', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.create_index(op.f('ix_meetings_organizer_user_id'), 'meetings', ['organizer_user_id'], unique=False)
    op.create_index(op.f('ix_meeting_summaries_embedding_hnsw'), 'meeting_summaries', ['embedding'], unique=False, postgresql_ops={'embedding': 'vector_cosine_ops'}, postgresql_using='hnsw')
    op.alter_column('integrations', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.create_index(op.f('ix_chunks_embedding_hnsw'), 'chunks', ['embedding'], unique=False, postgresql_ops={'embedding': 'vector_cosine_ops'}, postgresql_using='hnsw')
    op.drop_index(op.f('ix_workflow_step_runs_workflow_run_id'), table_name='workflow_step_runs')
    op.drop_index(op.f('ix_workflow_step_runs_id'), table_name='workflow_step_runs')
    op.drop_table('workflow_step_runs')
    op.drop_index(op.f('ix_workflow_approvals_workflow_run_id'), table_name='workflow_approvals')
    op.drop_index(op.f('ix_workflow_approvals_status'), table_name='workflow_approvals')
    op.drop_index(op.f('ix_workflow_approvals_id'), table_name='workflow_approvals')
    op.drop_table('workflow_approvals')
    op.drop_index(op.f('ix_workflow_runs_v2_workflow_id'), table_name='workflow_runs_v2')
    op.drop_index(op.f('ix_workflow_runs_v2_status'), table_name='workflow_runs_v2')
    op.drop_index(op.f('ix_workflow_runs_v2_id'), table_name='workflow_runs_v2')
    op.drop_table('workflow_runs_v2')
    op.drop_index(op.f('ix_workflows_title'), table_name='workflows')
    op.drop_index(op.f('ix_workflows_id'), table_name='workflows')
    op.drop_table('workflows')
    # ### end Alembic commands ###
